# Site settings
title: DG Kwon
url: "http://donggeunkwon.github.io"
google_analytics: "G-38HRD4JLW4" # GT-PBKLDRHJ

# Author
author:
  name: Donggeun Kwon
  desc: PhD Candidate in Korea Univ.
  email: donggeun.kwon@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: donggeun.kwon@gmail.com
  facebook: 
  github: donggeunkwon
  instagram:
  steam:
  twitter: dg_kwon
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/post/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
